# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(600, 400)
        LoginWindow.setAutoFillBackground(False)
        LoginWindow.setStyleSheet("background-color: rgb(233, 250, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginWindow)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginLayout = QtWidgets.QVBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(LoginWindow)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(LoginWindow)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(LoginWindow)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginWindow)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.loginLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttonLayout.setSpacing(19)
        self.buttonLayout.setObjectName("buttonLayout")
        self.loginButton = QtWidgets.QPushButton(LoginWindow)
        self.loginButton.setObjectName("loginButton")
        self.buttonLayout.addWidget(self.loginButton)
        self.cancelButton = QtWidgets.QPushButton(LoginWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.loginLayout.addLayout(self.buttonLayout)
        self.horizontalLayout.addLayout(self.loginLayout)
        self.imageLayout = QtWidgets.QVBoxLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(300, 500))
        self.label.setPixmap(QtGui.QPixmap("image1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.imageLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.imageLayout)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.usernameLabel.setText(_translate("LoginWindow", "Username:"))
        self.passwordLabel.setText(_translate("LoginWindow", "Password:"))
        self.loginButton.setText(_translate("LoginWindow", "Login"))
        self.cancelButton.setText(_translate("LoginWindow", "Cancel"))
